package com.crm.utility;

import java.io.FileOutputStream;
import java.util.Date;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

@Component
public class PdfGenerator {
	 private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
	            Font.BOLD);
	    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
	            Font.BOLD);
	    
	    
	    public  void generatePDF(String filePath, String firstName,String lastName, String emailId, Long mobile, String model, 
int amount) {
	        try {
	            Document document = new Document();
	            PdfWriter.getInstance(document, new FileOutputStream(filePath));
	            document.open();
	            addMetaData(document);
	            addTitleAndTable(document,firstName,lastName,emailId,mobile.toString(),model,String.valueOf(amount));
	           
	            document.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
	    }

	    // iText allows to add metadata to the PDF which can be viewed in your Adobe
	    // Reader
	    // under File -> Properties
	    private static void addMetaData(Document document) {
	        document.addTitle("My first PDF");
	        document.addSubject("Using iText");
	        document.addKeywords("Java, PDF, iText");
	        document.addAuthor("Lars Vogel");
	        document.addCreator("Lars Vogel");
	    }

	    private static void addTitleAndTable(Document document,String firstName,String lastName, String emailId, String mobile, String model,String amount)
	            throws DocumentException {
	        Paragraph preface = new Paragraph();
	        
	        
	        preface.add(new Paragraph("Billing Details", catFont));

	       
	        preface.add(new Paragraph(
	                "Report generated by: " + "XYZ Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
	                smallBold));
	       
	        document.add(preface);  
	        document.add( Chunk.NEWLINE );
	        document.add( Chunk.NEWLINE );
	        
	        
	        PdfPTable table = new PdfPTable(2);
	        table.setWidthPercentage(100);
	        // t.setBorderColor(BaseColor.GRAY);
	        // t.setPadding(4);
	        // t.setSpacing(4);
	        // t.setBorderWidth(1);

	        PdfPCell c1 = new PdfPCell(new Phrase("Costumer Detail"));
	        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	        c1.setColspan(2);
	        table.addCell(c1);



	        table.addCell("Costumer First Name");
	        table.addCell(firstName);
	        table.addCell("Cosyumer Last Name");
	        table.addCell(lastName);
	        table.addCell("Email Id");
	        table.addCell(emailId);
	        table.addCell("Phone Number");
	        table.addCell(mobile);
	        table.addCell("Model");
	        table.addCell(model);
	        table.addCell("Amount");
	        table.addCell(amount);
	        document.add(table);
	         
	        document.close();
	    }

		
	
}

